name: RisingOS GSI

on:
  workflow_dispatch:
jobs:
  test:
    name: Build GSIs using foss.crave.io

    runs-on: self-hosted

    steps:
    - name: Cleanup
      run: rm -rf *
    - name: Create workspace
      run: mkdir lion
      continue-on-error: true
    - name: Enter Workspace
      run: cd lion 
      continue-on-error: true
      # Check-out in order to access the repository's files.
    - name: Check-out to repository
      uses: actions/checkout@v4      
    - name: Exports
      run: |
        export BUILD_HOSTNAME=crave
        export BUILD_USERNAME=lion-development
    - name: Run Script
      run: bash build.sh
      # Only reach this when the user killed the workflow.
    - name: Execute if the job is cancelled
      if: ${{ cancelled() }}
      run: crave stop --all
    - name: Find output file
      run: |
        mv */*.zip .
    - name: Upload to Release
      uses: softprops/action-gh-release@v1
      with:
        files: | 
          *.zip
        name: LineageOS-20-${{ github.run_id }}
        tag_name: ${{ github.run_id }}
        body: |
          Target: lion
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
